### ISSUE TITLE
请问这种问题怎么解决

### ISSUE THREAD

**Issue by DTEX123** [NeutrinoC/Auto_GirlsFrontline#4]
Traceback (most recent call last):
  File "A:\MuMu\Auto_GirlsFrontline-master\autoLSupport\autoLSupport.py", line 204, in <module>
    if isMainMenu():
  File "A:\MuMu\Auto_GirlsFrontline-master\autoLSupport\autoLSupport.py", line 161, in isMainMenu
    return imageCompare(initImage,capImage)
  File "A:\MuMu\Auto_GirlsFrontline-master\autoLSupport\autoLSupport.py", line 115, in imageCompare
    (score, diff) = structural_similarity(gray_img1, gray_img2, full=True)
  File "E:\Python\lib\site-packages\skimage\metrics\_structural_similarity.py", line 89, in structural_similarity
    check_shape_equality(im1, im2)
  File "E:\Python\lib\site-packages\skimage\_shared\utils.py", line 157, in check_shape_equality
    raise ValueError('Input images must have the same dimensions.')
ValueError: Input images must have the same dimensions.
搞不清楚这个图片尺寸是怎么回事
另外老哥8-1n前面的法官用格里芬梯队就能过，祝早日出8-1n☺

**Comment by NeutrinoC** [comment]
我猜你肯定没有看我的程序，我简单讲一下吧，在运行的时候会不停地截取局部界面，这个局部界面是按照和模拟器窗口固定比例截取的，所以你的模拟器分辨率设置越高，模拟器窗口就越大，那么截取出来的图片也就越大。那么，我们截取出来的图片要做什么？是要和预存好的图片做对比，但是我预存的图片是在800*400的模拟器分辨率下截取出来的，如果你的模拟器分辨率是1200*600，那么你的图片就比我预存的图片大，自然就会“Input images must have the same dimensions.”
那么怎么解决？首先，既然你没有看过我的程序，那么就请使用MuMu模拟器，并且自定义分辨率为800*400，程序原封不动，我保证能够运行
然后8-1n我最近造出了第二只zas，程序已经写好了，测试几天没问题就会上传

**Comment by DTEX123** [comment]
谢谢大佬
抱歉，我这边替换错图片了
